apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbvedtaksstottefs
  namespace: default
  cluster:
    - prod-fss
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbvedtaksstottefs/veilarbvedtaksstottefs:{{version}}
  port: 80
  liveness:
    path: isAlive
    initialDelay: 15
  readiness:
    path: isReady
    initialDelay: 15
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: "1"
      memory: 1Gi
  ingresses:
    - https://veilarbvedtaksstottefs.nais.adeo.no
    - https://app.adeo.no/veilarbvedtaksstottefs
