apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbvedtaksstottefs
  namespace: obo
  labels:
    team: obo
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/poao/poao-frontend:2025.11.05_09.25-b34a8e35f6cc
  port: 8080
  ingresses:
    - https://veilarbvedtaksstottefs.intern.nav.no
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  env:
    - name: JSON_CONFIG
      value: >
        {
          "cors": {
            "origin": "https://veilarbpersonflate.intern.nav.no"
          },
          "header": {
            "corp": {
              "policy": "cross-origin"
            }
          }
        }
