apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbvedtaksstottefs
  namespace: obo
  labels:
    team: obo
spec:
  image: ghcr.io/navikt/poao-frontend/poao-frontend:2023.01.13_08.09-36c09678654f
  port: 8080
  ingresses:
    - https://veilarbvedtaksstottefs.intern.nav.no
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  gcp:
    buckets:
      - name: obo-veilarbvedtaksstottefs-prod
        cascadingDelete: false
  env:
    - name: JSON_CONFIG
      value: >
        {
          "cors": {
            "origin": "https://veilarbpersonflate.intern.nav.no"
          },
          "gcs": {
            "bucketName": "obo-veilarbvedtaksstottefs-prod"
          }
        }
