apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: veilarbvedtaksstottefs
  namespace: obo
  labels:
    team: obo
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/poao/poao-frontend:2024.11.12_09.35-97ae4c05891f
  port: 8080
  ingresses:
    - https://veilarbvedtaksstottefs.intern.nav.no
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  gcp:
    buckets:
      - name: obo-veilarbvedtaksstottefs-prod
        cascadingDelete: false
  env:
    - name: JSON_CONFIG
      value: >
        {
          "cors": {
            "origin": "https://veilarbpersonflate.intern.nav.no"
          },
          "header": {
            "corp": {
              "policy": "cross-origin"
            }
          },
          "gcs": {
            "bucketName": "obo-veilarbvedtaksstottefs-prod"
          }
        }
