import { useState } from 'react';
import constate from 'constate';

export enum ModalType {
	INGEN = 'INGEN',
	BEKREFT_SEND_VEDTAK = 'BEKREFT_SEND_VEDTAK',
	LASTER = 'LASTER_DATA',
	BEKREFT_SLETT_UTKAST = 'BEKREFT_SLETT_UTKAST',
	BEKREFT_TA_OVER_UTKAST = 'BEKREFT_TA_OVER_UTKAST',
	BEKREFT_AVBRYT_BESLUTTER_PROSESS = 'BEKREFT_AVBRYT_BESLUTTER_PROSESS',
	BEKREFT_SEND_TIL_GODKJENNING = 'BEKREFT_SEND_TIL_GODKJENNING',
	FEIL_VED_OPPRETTING_AV_UTKAST = 'FEIL_VED_OPPRETTING_AV_UTKAST',
	FEIL_UTSENDING_STOPPET = 'FEIL_UTSENDING_STOPPET',
	FEIL_VED_FORHANDSVISNING = 'FEIL_VED_FORHANDSVISNING',
	FEIL_VED_SENDING = 'FEIL_VED_SENDING',
	FEIL_VED_SLETTING = 'FEIL_VED_SLETTING',
	FEIL_VED_OVERTAKELSE = 'FEIL_VED_OVERTAKELSE',
	FEIL_VED_VISNING = 'FEIL_VED_VISNING',
	FEIL_VED_LAGRING = 'FEIL_VED_LAGRING',
	FEIL_VED_BLI_BESLUTTER = 'FEIL_VED_BLI_BESLUTTER',
	FEIL_VED_START_BESLUTTER_PROSESS = 'FEIL_VED_START_BESLUTTER_PROSESS',
	FEIL_VED_AVBRYT_BESLUTTER_PROSESS = 'FEIL_VED_AVBRYT_BESLUTTER_PROSESS',
	FEIL_VED_UTSENDING_AV_DIALOG_MELDING = 'FEIL_VED_UTSENDING_AV_DIALOG_MELDING',
	FEIL_VED_OPPDATER_BESLUTTER_PROSESS_STATUS = 'FEIL_VED_OPPDATER_BESLUTTER_PROSESS_STATUS',
	FEIL_VED_GODKJENT_AV_BESLUTTER = 'FEIL_VED_GODKJENT_AV_BESLUTTER',
	FEIL_VED_VALIDERING_AV_UTKAST = 'FEIL_VED_VALIDERING_AV_UTKAST'
}

export const [ModalStoreProvider, useModalStore] = constate(() => {
	const [modalType, setModalType] = useState<ModalType>(ModalType.INGEN);
	const [modalProps, setModalProps] = useState<any>({});

	const showModal = (type: ModalType, props: object = {}) => {
		setModalProps(props);
		setModalType(type);
	};

	const resetModalType = () => {
		setModalType(ModalType.INGEN);
	};

	return { modalType, modalProps, showModal, resetModalType };
});
