enum OyblikksbildeType {
	CV_OG_JOBBPROFIL = 'CV_OG_JOBBPROFIL',
	REGISTRERINGSINFO = 'REGISTRERINGSINFO',
	EGENVURDERING = 'EGENVURDERING',
	ARBEIDSSOKKERREGISTRET = 'ARBEIDSSOKKERREGISTRET'
}

export default OyblikksbildeType;
