enum OyblikksbildeType {
	CV_OG_JOBBPROFIL = 'CV_OG_JOBBPROFIL',
	REGISTRERINGSINFO = 'REGISTRERINGSINFO',
	EGENVURDERING = 'EGENVURDERING',
	ARBEIDSSOKERREGISTRET = 'ARBEIDSSOKERREGISTRET'
}

export default OyblikksbildeType;
