enum OyblikksbildeType {
	CV_OG_JOBBPROFIL = 'CV_OG_JOBBPROFIL', // Har fått navnet jobbønsker i etterkant
	REGISTRERINGSINFO = 'REGISTRERINGSINFO',
	EGENVURDERING = 'EGENVURDERING',
	ARBEIDSSOKERREGISTRET = 'ARBEIDSSOKERREGISTRET'
}

export default OyblikksbildeType;
