export enum SkjemaLagringStatus {
	INGEN_ENDRING = 'INGEN_ENDRING',
	ENDRING_IKKE_LAGRET = 'ENDRING_IKKE_LAGRET',
	LAGRER = 'LAGRER',
	ALLE_ENDRINGER_LAGRET = 'ALLE_ENDRINGER_LAGRET',
	LAGRING_FEILET = 'LAGRING_FEILET'
}
