export enum AksjonType {
    KLAR_TIL_BESLUTTER = 'KLAR_TIL_BESLUTTER',
    BLI_BESLUTTER = 'BLI_BESLUTTER',
    TA_OVER_SOM_BESLUTTER = 'TA_OVER_SOM_BESLUTTER',
    TA_OVER_SOM_VEILEDER = 'TA_OVER_SOM_VEILEDER',
    KVALIFISERT = 'KAVLIFISERT',
    OPPRETTET_UKAST = 'OPPRETTET_UKAST'
}