export enum MeldingType {
    MANUELL = 'MANUELL',
    SYSTEM = 'SYSTEM'
}

export enum MeldingUnderType {
    UTKAST_OPPRETTET = 'UTKAST_OPPRETTET',
    BESLUTTER_PROSESS_STARTET = 'BESLUTTER_PROSESS_STARTET',
    BLI_BESLUTTER = 'BLI_BESLUTTER',
    GODSKJENT_AV_BESLUTTER = 'GODSKJENT_AV_BESLUTTER',
    TA_OVER_SOM_BESLUTTER = 'TA_OVER_SOM_BESLUTTER',
    TA_OVER_SOM_VEILEDER = 'TA_OVER_SOM_VEILEDER'
}
