export enum VarselType {
	VEDTAK_SENT_SUKSESS = 'VEDTAK_SENT_SUKSESS',
	TATT_OVER_SOM_VEILEDER = 'TATT_OVER_SOM_VEILEDER',
	TATT_OVER_SOM_BESLUTTER = 'TATT_OVER_SOM_BESLUTTER',
	UTKAST_OPPDATERT = 'UTKAST_OPPDATERT',
	BESLUTTERPROSESS_TIL_VEILEDER = 'BESLUTTERPROSESS_TIL_VEILEDER',
	BESLUTTERPROSESS_TIL_BESLUTTER = 'BESLUTTERPROSESS_TIL_BESLUTTER',
	BESLUTTERPROSESS_GODKJENT = 'BESLUTTERPROSESS_GODKJENT'
}
