name: Test
on: push

jobs:
  update-dev:
    name: Upload files to dev GCS
    if: github.ref == 'refs/heads/gcp-migrering'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Build application
        run: npm run build
        env:
          PUBLIC_URL: https://veilarbvedtaksstottefs.dev.intern.nav.no
      - name: Setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCS_SA_KEY_DEV }}
          export_default_credentials: true
      - name: Upload files to GCS
        run: gsutil -m rsync -r build gs://veilarbvedtaksstottefs-dev
